routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('basicos', 'Basicocontroller');

Route::get('basicos/{id}/destroy', [
"uses"=> "basicocontroller@destroy",
 "as" => "basicos.destroy"
]);

app/Person.php
<?php

namespace pasos;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
      protected $table="persons";
      protected  $primarykey="id";

      protected $fillable=["name","last_name"];



}

app/User.php
<?php

namespace pasos;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Basicocontroller.php
<?php

namespace pasos\Http\Controllers;

use Illuminate\Http\Request;

use pasos\Http\Requests;

use pasos\Person;

class Basicocontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
            $persons =Person::all();

        return  view('layout.inicio')->with("datos",$persons);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("layout.parte1");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         Person::create($request->all());
          return Redirect('basicos');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {


        return "has llegado mostrar";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $persona =   Person::findOrFail($id);
     /**      {{--return  View ("layout.Editar",["persona"=> $persona])}}

    *
    */
        return  View ("layout.Editar")->with('persona', $persona);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
                        $datos = person::findOrFail($id);
                        $datos-> fill($request->all());
                        $datos->save();
                          return redirect('basicos');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $datos = Person::findOrFail($id);
        $datos->delete();
        return redirect('basicos');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace pasos\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/layout/editar.blade.php
@extends('layout.template')

@section('title','titulo')


@section('contenido')

<div class="container">
            <h1>EDITAR DATOS</h1></br>


{!! Form::model($persona, ['route' => ['basicos.update', $persona->id], 'method' => 'PUT' , "class"=>"form-horizontal"]) !!}

<div class="form-group ">
  {!! Form::label("name","Nombre",[" class"=>"control-label col-md-3"])!!}
  <div class="col-md-6">
  {!!Form::text("name",null,["class"=>"form-control ", "placeholder"=>"Ingrese Primer Nombe "])!!}
  </div>
</div>

<div class="form-group">
  {!! Form::label('Last_name',"Segundo Nombre",["class"=>"control-label col-md-3"]) !!}
  <div class="col-md-6">
      {!!Form::text('last_name',null,["class"=>"form-control",'placeholder'=>'ingrese Segundo Nombre'])!!}
  </div>

</div>

{!! Form::submit('Editar', ['class' => 'btn btn-primary  ']) !!}

{!! Form::close() !!}


</div>
<!-- ciere de div-->
<!--
 * <form class="form-horizontal" action="index.html" method="post">
 */

    <div class="form-group col-md-offset-4">
          <label for="Name" class="col-md-1 col-md-offset-3">Nombre:</label>
          <div class="col-md-4">
            <input type="text" class="form-control " id="Name" placeholder="ingrese Nombre">

          </div>

  </div>
  <div class="form-group">
        <label for="" class="col-md-1 col-md-offset-3">Segundo Nombre</label>
        <div class="col-md-4">
            <input type="text" class="form-control" id="" placeholder="Segundo Nombre">
        </div>


</div>
    <button type="submit" name="button" class=" btn btn-primary">Ingresar Datos</button>
</form>-->




@endsection

resources/views/layout/inicio.blade.php
@extends('layout.template')

@section('title','titulo')


@section('contenido')

<h1>registrados</h1>
<div class="table-responsive">


<table class="table">

  <tr>
  <td>Nombre</td>
    <td>last_name</td>
    <td> Accion</td>
  @foreach ($datos as $dato)
  </tr>

<td>{!! $dato->name  !!}</td>
<td>{!!$dato->last_name !!}</td>
<td> <a href="{{route("basicos.edit",$dato->id)}}" class="btn btn-success">Editar</a>
          <a href="{{route("basicos.destroy",$dato->id)}}" class="btn btn-danger">Eliminar</a>
</td>
@endforeach




</table>
</div>
@endsection

resources/views/layout/parte1.blade.php
@extends('layout.template')

@section('title','titulo')


@section('contenido')

<div class="container">
            <h1>Ingresar Datos</h1></br>
<!--
 * <form class="form-horizontal" action="index.html" method="post">
 */

    <div class="form-group col-md-offset-4">
          <label for="Name" class="col-md-1 col-md-offset-3">Nombre:</label>
          <div class="col-md-4">
            <input type="text" class="form-control " id="Name" placeholder="ingrese Nombre">

          </div>

  </div>
  <div class="form-group">
        <label for="" class="col-md-1 col-md-offset-3">Segundo Nombre</label>
        <div class="col-md-4">
            <input type="text" class="form-control" id="" placeholder="Segundo Nombre">
        </div>


</div>
    <button type="submit" name="button" class=" btn btn-primary">Ingresar Datos</button>
</form>-->
{!! Form::open(['method' => 'POST', 'route' => 'basicos.store', 'class' => 'form-horizontal']) !!}
<div class="form-group ">

  {!! Form::label("name","Nombre",[" class"=>"control-label col-sm-3"])!!}
  <div class="col-md-6">
  {!!Form::text("name",null,["class"=>"form-control ", "placeholder"=>"Ingrese Primer Nombe "])!!}
  </div>

</div>
<div class="form-group">
  {!! Form::label('Last_name',"Segundo Nombre",["class"=>"control-label col-sm-3"]) !!}
  <div class="col-md-6">
      {!!Form::text('last_name',null,["class"=>"form-control",'placeholder'=>'ingrese Segundo Nombre'])!!}
  </div>

</div>

{!! Form::submit('Enviar', ['class' => 'btn btn-primary  ']) !!}



{!! Form::close() !!}

</div>
<!-- ciere de div-->



@endsection

resources/views/layout/template.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@yield('title')</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
   <link rel="stylesheet"   href="{{ asset('asset/css/style.css ')}} "  media="screen" title="no title">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
@section('navbar')
  <nav class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li ><a href="{{route('basicos.index')}}">Inicio</a></li>
              <li><a href="{{route('basicos.create')}}">Ingresar</a></li>

            </ul>

            </div>
              </div>
</nav>
@show
<div class="container">
@section('contenido')


         <h1>Text Here</h1>
@show
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </body>
</html>